try multinode

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -124,7 +124,7 @@ jobs:
           echo $image
           echo "TEST_IMAGE_URI=$image" >> $GITHUB_OUTPUT
 
-      - name: "AoT Model Sharding"
+      - name: "Model Optimization Step"
         working-directory: tests/integration
         run: |
           echo ${{ steps.compute-image-uri.outputs.TEST_IMAGE_URI}}
@@ -132,14 +132,14 @@ jobs:
           sudo rm -rf models
           python3 llm/prepare.py ${{ matrix.test.test_handler }} ${{ matrix.test.test_model_config }}
           ./launch_container.sh ${{ steps.compute-image-uri.outputs.TEST_IMAGE_URI }} $PWD/models lmi sm_neo_context
-      # - name: "Fast Model Loading - Local Mode"
-      #   working-directory: tests/integration
-      #   run: |
-      #     # test inference
-      #     ./launch_container.sh $DJL_CONTAINER_REPO:$lmi-$OVERRIDE_IMAGE_TAG_SUFFIX $PWD/models/compiled lmi serve
-      #     python3 llm/client.py ${{ matrix.test.test_handler }} ${{ matrix.test.test_serve_config }}
-      #     # clean up
-      #     docker rm -f $(docker ps -aq) || true
+      - name: "Local Serving Test"
+        working-directory: tests/integration
+        run: |
+          # test inference
+          ./launch_container.sh ${{ steps.compute-image-uri.outputs.TEST_IMAGE_URI }} $PWD/models/compiled lmi multi_node serve
+          python3 llm/client.py ${{ matrix.test.test_handler }} ${{ matrix.test.test_serve_config }}
+          # clean up
+          docker rm -f $(docker ps -aq) || true
       
       - name: On fail step
         if: ${{ failure() }}
